### ISSUE TITLE
Improved Docker Daemon Detection & Error Messaging

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1137]
We should have better error messaging for when the docker daemon is not running.

Currently, if I create a new project, and run `polywrap infra up --modules=eth-ens-ipfs`, it fails with the following error:
```
Using infra modules: 
- eth-ens-ipfs


/Users/dorgjelli/Dev/Repos/demos/impl-aggregator/wrapper/interface/node_modules/gluegun/build/index.js:13
    throw up;
    ^
{
  exitCode: 255,
  err: 'Traceback (most recent call last):\n' +
    '  File "urllib3/connectionpool.py", line 670, in urlopen\n' +
    '  File "urllib3/connectionpool.py", line 392, in _make_request\n' +
    '  File "http/client.py", line 1255, in request\n' +
    '  File "http/client.py", line 1301, in _send_request\n' +
    '  File "http/client.py", line 1250, in endheaders\n' +
    '  File "http/client.py", line 1010, in _send_output\n' +
    '  File "http/client.py", line 950, in send\n' +
    '  File "docker/transport/unixconn.py", line 43, in connect\n' +
    'FileNotFoundError: [Errno 2] No such file or directory\n' +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "requests/adapters.py", line 439, in send\n' +
    '  File "urllib3/connectionpool.py", line 726, in urlopen\n' +
    '  File "urllib3/util/retry.py", line 410, in increment\n' +
    '  File "urllib3/packages/six.py", line 734, in reraise\n' +
    '  File "urllib3/connectionpool.py", line 670, in urlopen\n' +
    '  File "urllib3/connectionpool.py", line 392, in _make_request\n' +
    '  File "http/client.py", line 1255, in request\n' +
    '  File "http/client.py", line 1301, in _send_request\n' +
    '  File "http/client.py", line 1250, in endheaders\n' +
    '  File "http/client.py", line 1010, in _send_output\n' +
    '  File "http/client.py", line 950, in send\n' +
    '  File "docker/transport/unixconn.py", line 43, in connect\n' +
    "urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\n" +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "docker/api/client.py", line 214, in _retrieve_server_version\n' +
    '  File "docker/api/daemon.py", line 181, in version\n' +
    '  File "docker/utils/decorators.py", line 46, in inner\n' +
    '  File "docker/api/client.py", line 237, in _get\n' +
    '  File "requests/sessions.py", line 543, in get\n' +
    '  File "requests/sessions.py", line 530, in request\n' +
    '  File "requests/sessions.py", line 643, in send\n' +
    '  File "requests/adapters.py", line 498, in send\n' +
    "requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\n" +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "docker-compose", line 3, in <module>\n' +
    '  File "compose/cli/main.py", line 81, in main\n' +
    '  File "compose/cli/main.py", line 200, in perform_command\n' +
    '  File "compose/cli/command.py", line 60, in project_from_options\n' +
    '  File "compose/cli/command.py", line 152, in get_project\n' +
    '  File "compose/cli/docker_client.py", line 41, in get_client\n' +
    '  File "compose/cli/docker_client.py", line 170, in docker_client\n' +
    '  File "docker/api/client.py", line 197, in __init__\n' +
    '  File "docker/api/client.py", line 221, in _retrieve_server_version\n' +
    "docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\n" +
    '[8334] Failed to execute script docker-compose\n',
  out: ''
}
error Command failed with exit code 1.
```

# Repro Steps
`npx polywrap create wasm interface new-interface`
`cd new-interface`
`nvm use`
`yarn`
`yarn test:env:up`

^^ make sure docker daemon is not running

**Comment by dOrgJelli** [comment]
Oh wow, nvm, forgot that on my MacBook I needed to manually start my docker daemon in the background.

I think we should improve the error output though, since it should have told me explicitly "docker daemon is not running".
