### ISSUE TITLE
CLI: Building Interfaces Shouldn't Require Docker

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1355]
**Describe the bug**
Currently when you build a Polywrap interface project, it fails if the docker daemon isn't running. Docker is not required since building interfaces just involves parsing the schema and outputting the wrap.info manifest file.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
- create interface project
- don't have docker daemon running
- run `polywrap build`
- see error asking for docker daemon to be started

**Expected behavior**
Should successfully build interface.

**Screenshots / logs**
```
$ lerna run build --scope @polywrap/*-interface
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "@polywrap/*-interface"
lerna info filter [ '@polywrap/*-interface' ]
lerna info Executing command in 5 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@polywrap/file-system-interface'
lerna ERR! yarn run build stdout:
$ node ../../../dependencies/node_modules/polywrap/bin/polywrap build
🔄 Manifest loaded from ./polywrap.yaml
✅ Manifest loaded from ./polywrap.yaml
> docker version
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
warning package.json: No license field
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
/Users/dorgjelli/Dev/Repos/toolchain-b/dependencies/node_modules/polywrap/build/lib/build-strategies/strategies/DockerVMStrategy.js:80
            throw new Error(intl_1.intlMsg.lib_docker_noInstall());
                  ^

Error: Docker executable not found in PATH
    at new DockerVMBuildStrategy (/Users/dorgjelli/Dev/Repos/toolchain-b/dependencies/node_modules/polywrap/build/lib/build-strategies/strategies/DockerVMStrategy.js:80:19)
    at createBuildStrategy (/Users/dorgjelli/Dev/Repos/toolchain-b/dependencies/node_modules/polywrap/build/commands/build.js:139:20)
    at /Users/dorgjelli/Dev/Repos/toolchain-b/dependencies/node_modules/polywrap/build/commands/build.js:168:37
    at step (/Users/dorgjelli/Dev/Repos/toolchain-b/dependencies/node_modules/polywrap/build/commands/build.js:44:23)
    at Object.next (/Users/dorgjelli/Dev/Repos/toolchain-b/dependencies/node_modules/polywrap/build/commands/build.js:25:53)
    at fulfilled (/Users/dorgjelli/Dev/Repos/toolchain-b/dependencies/node_modules/polywrap/build/commands/build.js:16:58)
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@polywrap/file-system-interface'
```

**Relevant environment details:**
- Polywrap CLI Version: `0.9.3`
- OS: Mac OS

**Comment by cbrzn** [comment]
hey @pileks this issue can be closed, right?

**Comment by pileks** [comment]
@cbrzn You're right, we resolved this temporarily using an empty build strategy and later removed the empty build strategy when we split `codegen` and `build` as part of https://github.com/polywrap/toolchain/pull/1385

**Comment by dOrgJelli** [comment]
Reopening as this seems to still be an issue in version `0.10.0-pre.8`.
