### ISSUE TITLE
`polywrap deploy`'s IPFS module fails with node version 18

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1803]
**Describe the bug**
When running `polywrap deploy` with the ipfs deploy module enabled, and node version 18 is being used, it fails with the following error:
```
$ polywrap deploy -o deployment.json
🔄 Manifest loaded from ./polywrap.deploy.yaml
✅ Manifest loaded from ./polywrap.deploy.yaml
🔄 Load manifest extension from ./.polywrap/deploy/modules/ipfs/polywrap.deploy.ext.json
🔄 Load manifest extension from ./.polywrap/deploy/modules/http/polywrap.deploy.ext.json
✅ Load manifest extension from ./.polywrap/deploy/modules/ipfs/polywrap.deploy.ext.json
✅ Load manifest extension from ./.polywrap/deploy/modules/http/polywrap.deploy.ext.json


Executing 'ipfs_deploy' deployment DeployJob: 

- ipfs_deploy
- http_deploy


Executing step: 'ipfs_deploy', with URI: 'wrap://fs/./build'
.../node_modules/polywrap/build/lib/deploy/DeployJob.js:121
                        throw new Error("Failed to execute step '".concat(step.name, "'. Error: ").concat(e_2));
                              ^

Error: Failed to execute step 'ipfs_deploy'. Error: TypeError: RequestInit: duplex option is required when sending a body.
    at DeployJob.<anonymous> (.../node_modules/polywrap/build/lib/deploy/DeployJob.js:121:31)
    at step (.../node_modules/polywrap/build/lib/deploy/DeployJob.js:44:23)
    at Object.throw (.../node_modules/polywrap/build/lib/deploy/DeployJob.js:25:53)
    at rejected (.../node_modules/polywrap/build/lib/deploy/DeployJob.js:17:65)

Node.js v18.15.0
error Command failed with exit code 1.
```

**Comment by dOrgJelli** [comment]
This has been fixed
